version: 2.1
jobs:
  install:
    docker:
      - image: cypress/base:14.17.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-tests-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          paths:
            - ~/.cache
            - ~/.npm
          key: dependency-cache-tests-{{ checksum "yarn.lock" }}
  test:
    docker:
      - image: makerdaodux/dapptools-node-circleci-docker
    resource_class: large
    steps:
      - checkout
      - run: yarn install --frozen-lockfile --non-interactive
      - run:
          name: Run tests
          command: |
            source /home/circleci/setup-env.sh
            yarn e2e:headless
            yarn test:ci
            USE_FS_CACHE=1 yarn build
            yarn add --dev codecov
            ./node_modules/.bin/codecov
workflows:
  version: 2
  mainflow:
    jobs:
      - install
      - test:
          requires:
            - install
