name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # TODO: Build requires having configured the sentry credentials in the CI. 
          #build: yarn run build
          lint: yarn run lint
          start: npm start
      - name: Unit tests
        run: yarn test:ci